apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: hbserviceaccount
  name: hbserviceaccount-token
  namespace: default
type: kubernetes.io/service-account-token